services:
  # Фронтенд (React/Vite + Nginx)
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # Заставляем web запускаться всегда (даже если бот упал)

  # Бэкэнд (Python Telegram Bot)
  bot:
    build:
      context: ./bot # Теперь контекст — только папка бота
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env # Путь к конфигам тоже поправь
    restart: unless-stopped
