server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Главное правило для React Router:
    # Пытаемся отдать файл (например, картинку или JS), затем директорию
    # Если ничего не найдено, всегда отдаем index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Опционально: Агрессивное кэширование статики Vite (папка assets имеет хэши в названиях)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
